version: "3.8"
services:
  rolplay:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - rolplay_db

  rolplay_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rolplay
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/DBMySQL:/var/lib/mysql
    ports:
      - 33060:3306
